# Generated by Django 3.0.7 on 2021-01-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STPHOHapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectyear',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
